.spi_depends_default: &spi_depends_default
  depends_components:
    - esp_mm  # for cache
    - esp_driver_spi
    - esp_driver_gpio
  depends_filepatterns:
    - components/driver/test_apps/components/test_driver_utils/**/*

components/esp_driver_spi/test_apps/master:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: not supported # TODO: IDF-8942
  <<: *spi_depends_default

components/esp_driver_spi/test_apps/param:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: not supported # TODO: IDF-8942
  <<: *spi_depends_default

components/esp_driver_spi/test_apps/slave:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: not supported # TODO: IDF-8942
  <<: *spi_depends_default

components/esp_driver_spi/test_apps/slave_hd:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1
    - if: SOC_SPI_SUPPORT_SLAVE_HD_VER2 != 1
  disable_test:
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: not supported # TODO: IDF-8942
  <<: *spi_depends_default
