# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_driver_parlio/test_apps/parlio:
  disable:
    - if: SOC_PARLIO_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET in ["esp32h2", "esp32p4"]
      temporary: true
      reason: IDF-9806 waiting for the fix of the bit shift issue after reset
  depends_components:
    - esp_driver_parlio
