# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_driver_usb_serial_jtag/test_apps/usb_serial_jtag:
  disable:
    - if: SOC_USB_SERIAL_JTAG_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET in ["esp32p4"]
      temporary: true
      reason: No runners.
  depends_components:
    - vfs
    - esp_driver_gpio
    - esp_driver_usb_serial_jtag
