# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/freertos/test_apps/freertos:
  disable:
    - if: IDF_TARGET == "esp32c5" or (CONFIG_NAME == "smp" and IDF_TARGET == "esp32p4")
      temporary: true
      reason: target(s) not supported yet  # TODO: [ESP32C5] IDF-8672

components/freertos/test_apps/orig_inc_path:
  enable:
    - if: IDF_TARGET in ["esp32"]
      reason: The feature only depends on the build system, nothing target-specific that needs to be tested
