# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/app_trace/test_apps:
  depends_components:
    - app_trace
    - esp_timer
    - soc
    - driver
    - esp_hw_support
  disable:
    - if: IDF_TARGET == "esp32c5"
      temporary: true
      reason: not support yet # TODO: [ESP32C5] IDF-8705
