components/vfs/test_apps:
  disable:
    - if: IDF_TARGET == "esp32c5"
      temporary: true
      reason: not support yet # TODO: [ESP32C5] IDF-8704
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c2", "esp32c3", "esp32c6", "esp32h2", "esp32s3"]
      temporary: true
      reason: lack of runners

  depends_components:
    - vfs
    - fatfs
    - spiffs
    - console
    - driver
